FROM memcached:1.5.7-alpine
# RUN echo "set timezone" \
#     && apk add --update tzdata \
#     && cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
#     && apk del tzdata \
#     && rm -rf /var/cache/apk
